<?php
$mediaUrl = $this->helper('Codazon\Shopbybrandpro\Helper\Wysiwyg\Images')->getBaseUrl();
$defaultThumbnail = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\View\Asset\Repository')->getUrl('Codazon_Shopbybrandpro/images/placeholder_thumbnail.jpg');
?>
<script>
require(['jquery', 'Codazon_Shopbybrandpro/js/browser'], function($) {
    var mediaUrl = '<?php echo $mediaUrl; ?>';
    var defaultThumbnail = '<?php echo $defaultThumbnail ?>';
    window.changePreviewImage = function(obj) {
        var $_input = $(obj);
        if ($_input.parent().find('.attached_image img').length > 0) {
            var $_img = $_input.parent().find('.attached_image img').first();
            $_img.attr('src', mediaUrl + $_input.val());
        }
    };
    window.clearValue = function(obj) {
        $_btn = $(obj);
        if ($_btn.parent().find('.input-image').length > 0) {
            var $_input = $_btn.parent().find('.input-image').first();
            $_input.val('');
        }
        if ($_btn.parent().find('.attached_image img').length > 0) {
            var $_img = $_btn.parent().find('.attached_image img').first();
            $_img.attr('src', defaultThumbnail);
        }
    }
});
</script>